app = "bot"

[[buildpacks]]
  uri = "https://github.com/heroku/heroku-buildpack-python"

[[services]]
  internal_port = 8080

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
